### ISSUE TITLE
Improve communication of where you are in the process

### ISSUE THREAD

**Issue by pglevy** [Bixal/complaint-screener#23]

**Comment by ghost** [comment]
- [x] design in figma

- [ ] feedback and discussion from team

- [ ] implement changes into repo

**Comment by ghost** [comment]
ready for some feedback in figma @pglevy @bnaolu

**Comment by ghost** [comment]
Action items:
- mockup a larger grouped progress bar within the individual 1-5 steps
- provide some global context with a process list before you get into the step indicator
- make the step text more dynamic to reveal more information(show where you are in the global context or section context similar to an accordion)
- instead of treating the step indicator as a singular component that show progress/information use a combo of the slider/progress bar being the global representation and the text and number circle being the internal steps description
