### ISSUE TITLE
q1-exit path

### ISSUE THREAD

**Issue by bnaolu** [Bixal/complaint-screener#52]
Going through the screener and saw that the q1 exit path leads to the "Unfortunately, we can't complete your request".
- Just wanted to double check if this was the correct path, and to confirm whether we're using the "You may still be able to file a complaint" option or not. 
- Also, buttons on this page either lead back to the question or allows users to continue filing, which may be confusing with the current heading.

**Comment by pglevy** [comment]
This is a fair point. The path is correct, but there are a couple of conflicting things going on:
- In general, we opted toward being lenient about letting people continue anyway, in case the examples weren't clear or they weren't sure.
- In this case though, it's pretty clear on the policy side that this form does not apply to these other people and orgs, and they probably shouldn't continue.

That said, I think the first point still applies here. People may know something we haven't accounted and shouldn't be prevented from continuing if we've provided them enough context.

So I can think we can address this with some copy changes.

**Comment by pglevy** [comment]
PS  - I removed the "invalid" label, because I think the intent of that is more to label the issue itself (meaning, as someone managing the issue log for this product, I think this issue someone has opened does not make sense or does not apply in some way, so let's ask for more information or not worry about it.)
